### ISSUE TITLE
App crash in docker

### ISSUE THREAD

**Issue by vadimicus** [cyberFund/cyber-markets#122]
Docker was launched by the command 
"docker run -e CONNECTORS_DEBUG='true' --rm cybernode/cm-connectors"

After that in console you can see stack trace :
```
12:32:06.529 [kafka-producer-network-thread | producer-2] o.a.kafka.clients.NetworkClient - Node -1 disconnected.
12:32:06.529 [kafka-producer-network-thread | producer-2] o.a.kafka.clients.NetworkClient - Connection to node -1 could not be established. Broker may not be available.
12:32:06.529 [kafka-producer-network-thread | producer-2] o.a.kafka.clients.NetworkClient - Give up sending metadata request since no node is available
12:32:06.533 [kafka-producer-network-thread | producer-1] o.a.kafka.clients.NetworkClient - Initialize connection to node -1 for sending metadata request
12:32:06.533 [kafka-producer-network-thread | producer-1] o.a.kafka.clients.NetworkClient - Initiating connection to node -1 at localhost:9092.
12:32:06.534 [kafka-producer-network-thread | producer-1] o.a.kafka.common.network.Selector - Connection with localhost/127.0.0.1 disconnected
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50)
	at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:95)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:359)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:326)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:432)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:224)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:162)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by litvintech** [comment]
Need to update README with new instruction

**Comment by hleb-albau** [comment]
No more actual.
